data_root: data/udacity
tasks: circuit1,circuit2
method: ewc
mode: continual
val_ratio: 0.2
split: stratified
bins: 15
preset: std
encode: null
T: null
gain: null
amp: null
epochs: 3
batch_size: 64
num_workers: 0
lr: 1e-4
seed: 42
out_base: outputs/runs
use-codecarbon: false
